Description: >
    Michael Thiem / Udacity Student
    CFN Template for deploying a VPC
Resources:
    SampleVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/20
            EnableDnsHostnames: true